### ISSUE TITLE
"roslaunch xpp_examples hyq_ex.launch" error

### ISSUE THREAD

**Issue by xinsongyan** [leggedrobotics/xpp#2]
When I try to lunch hyq example with: 
$ roslaunch xpp_examples hyq_ex.launch

I got the error:

xacro: Traditional processing is deprecated. Switch to --inorder processing!
To check for compatibility of your document, use option --check-order.
For more infos, see http://wiki.ros.org/xacro#Processing_Order
deprecated: xacro tags should be prepended with 'xacro' xml namespace.
Use the following script to fix incorrect usage:
        find . -iname "*.xacro" | xargs sed -i 's#<\([/]\?\)\(if\|unless\|include\|arg\|property\|macro\|insert_block\)#<\1xacro:\2#g'
when processing file: /opt/ros/kinetic/share/xpp_hyq/urdf/hyq.urdf.xacro

Unused block "origin"
XacroException(u'Unused block "origin"',)
when instantiating macro: hyq_trunk (/opt/ros/kinetic/share/xpp_hyq/urdf/hyq.urdf.xacro)
in file: /opt/ros/kinetic/share/xpp_hyq/urdf/hyq.urdf.xacro
while processing /opt/ros/kinetic/share/xpp_hyq/launch/hyq.launch:
Invalid <param> tag: Cannot load command parameter [hyq_rviz_urdf_robot_description]: command [/opt/ros/kinetic/share/xacro/xacro.py '/opt/ros/kinetic/share/xpp_hyq/urdf/hyq.urdf.xacro'] returned with code [2]. 

Param xml is <param command="$(find xacro)/xacro.py '$(find xpp_hyq)/urdf/hyq.urdf.xacro'" name="hyq_rviz_urdf_robot_description"/>
The traceback for the exception was written to the log file

**Comment by awinkler** [comment]
Thanks for pointing this out. This has now been fixed in #3, specifically here: https://github.com/leggedrobotics/xpp/pull/3/commits/12d074a22182111d0f3292295c3d769c350373f6 .

To use this fix, either clone the repo from master (`git clone git@github.com:leggedrobotics/xpp.git`)
or wait until version 1.0.4 has made it into the ros-kinetic debians (could take a few days).
